services:
  frontend:
    container_name: frontend
    build:
      context: ./front
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    networks:
      - app
    command: bash -c "npm install -g serve && serve -s build"
    depends_on:
      - backend
    restart: always

  backend:
    container_name: backend
    build:
      context: ./back
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    networks:
      - app
    depends_on:
      - bdd
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
    networks:
      - app
    restart: always

  bdd:
    container_name: bdd
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app
    restart: always

volumes:
  data:

networks:
  app:
