version: '3'

services:

  frontend:
    container_name: frontend
    build:
      context: ./front
      dockerfile: ./Dockerfile
    # Add environment variables securely using an env_file or secrets management system
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
      - REACT_APP_REDIRECT_URI=${REACT_APP_CLIENT_ID}
      - REACT_APP_FOTRYTWO_LOGIN_URL=${REACT_APP_CLIENT_ID}
      - REACT_APP_GOOGLE_LOGIN_URL=${REACT_APP_CLIENT_ID}
    volumes:
      - ./front:/workspace/front
      - ./front/node_modules:/workspace/front/node_modules
    networks:
      - app
    depends_on:
      - backend
    restart: always

  backend:
    container_name: backend
    build:
      context: ./back
      dockerfile: ./Dockerfile
    # env_file:
    #   - ./back/.env
    # Add environment variables securely using an env_file or secrets management system
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - jwtSecret=${jwtSecret}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FORTYTWO_CLIENT_ID=${FORTYTWO_CLIENT_ID}
      - FORTYTWO_CLIENT_SECRET=${FORTYTWO_CLIENT_SECRET}
    ports:
      - 5555:5555
    volumes:
      - ./back:/workspace/back
    networks:
      - app
    depends_on:
      - bdd
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
    networks:
      - app
    restart: always

  bdd:
    container_name: bdd
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app
    restart: always

volumes:
  data:

networks:
  app:
