services:

  frontend:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    env_file:
    - ./front/.env
    ports:
      - 4000:4000
    volumes:
      - ./front:/workspace/front
    networks:
      - app
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    env_file:
    - ./back/.env
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./back:/workspace/back
    networks:
      - app
    depends_on:
      - bdd
    restart: always

  nginx:
    build:
      context: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - ./front/build:/workspace/front/build
    networks:
      - app  

  bdd:
    image: postgres:latest
    env_file:
    - ./bdd.env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app

volumes:
  data:

networks:
  app: