services:

  backend:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    env_file:
    - ./back/back.env
    ports:
      - 3000:3000
    networks:
      - app
    depends_on:
      - bdd

  bdd:
    image: postgres:latest
    env_file:
    - ./bdd.env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app

volumes:
  data:

networks:
  app: