version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
        - 5434:5432
    environment:
      POSTFRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
    - backend
networks:
  backend: