version: '3.8'
services:
  back-dev-db-1:
    image: postgres:latest
    ports:
        - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
    - backend
  test-db:
    image: postgres:latest
    ports:
        - 5435:5432
    environment:
      POSTFRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
    - backend
networks:
  backend: