export {default as Home} from './Home/Home';
export {default as Signin} from './Signin/Signin';
export {default as Signup} from './Signup/Signup';
export {default as Profile} from './Profile/Profile';
export {default as ProfileEdit} from './ProfileEdit/ProfileEdit';
export {default as ProfileGameHistory} from './ProfileGameHistory/ProfileGameHistory';
export {default as Friends} from './Friends/Friends';
export {default as LeaderBoard} from './LeaderBoard/LeaderBoard';
export {default as Play} from './Play/Play';
export {default as JoinGame} from './JoinGame/JoinGame';
export {default as OnlineGames} from './OnlineGames/OnlineGames';
export {default as Spectate} from './Spectate/Spectate';
export {default as Auth2factor} from './Auth2factor/Auth2factor';
export {default as Dashboard} from './Dashboard/Dashboard';
export {default as ChatBox} from './ChatBox/ChatBox';

export {default as ProfileHeader} from './Dashboard/components/ProfileHeader'
export {default as NavFooter} from './Dashboard/components/NavFooter'
export {default as AllUsers} from './AllUsers/AllUsers'
export {default as NotFoundPage} from './NotFoundPage/NotFoundPage'
export {default as NotFoundPageDashboard} from './NotFoundPage/NotFoundDashboard'
export {default as ErrorPage} from './ErrorPage/ErrorPage'
